---
- name: install cobbler
  action: yum name={{ item }} state=installed
  with_items:
    - cobbler
    - fence-agents

- name: chkconfig on and start apache
  action: service name=httpd state=started enabled=yes

- name: chkconfig on and start cobblerd
  action: service name=cobblerd state=started enabled=yes

- name: chkconfig on and start xinetd
  action: service name=xinetd state=started enabled=yes

- name: copy xinetd configs
  copy: src={{ item }} dest=/etc/xinetd.d/
  with_items:
    - rsync
    - tftp
  notify: restart xinetd
  tags: xinetd-config

- name: ensure dhcp and named are chkconfiged on
  service: name={{ item }} state=started enabled=yes
  with_items:
    - named
    - dhcpd

