---
- name: install cobbler
  action: yum name={{ item }} state=installed
  with_items:
    - cobbler
    - fence-agents

- name: set selinux booleans for cobbler and httpd
  seboolean: name={{ item }} state=1 persistent=yes
  with_items:
    - httpd_can_network_connect_cobbler
    - httpd_serve_cobbler_files
    - cobbler_can_network_connect

- name: copy cobbler_unconfined selinux policy
  copy: src=cobbler_unconfined.pp dest=/root/
  notify: install cobbler_unconfined selinux policy

- meta: flush_handlers

- name: copy xinetd configs
  copy: src={{ item }} dest=/etc/xinetd.d/
  with_items:
    - rsync
    - tftp
  notify: restart xinetd
  tags: xinetd-config

- name: start and enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - httpd
    - xinetd
    - cobblerd
  notify: cobbler get loaders

