---
- name: restart cobblerd
  action: service name=cobblerd state=restarted

- name: restart httpd
  action: service name=httpd state=restarted

- name: restart xinetd
  action: service name=xinetd state=restarted

- name: cobbler sync
  action: raw cobbler sync

- name: restart named
  action: service name=named state=restarted
