---
- name: restart cobblerd
  action: service name=cobblerd state=restarted

- name: restart httpd
  action: service name=httpd state=restarted

- name: restart xinetd
  action: service name=xinetd state=restarted

- name: cobbler sync
  action: raw cobbler sync

- name: install cobbler_unconfined selinux policy
  shell: semodule -i /root/cobbler_unconfined.pp

- name: cobbler get loaders
  shell: cobbler get-loaders
  notify: cobbler signature update

- name: cobbler signature update
  shell: cobbler signature update
  notify: cobbler sync

